"""
Storage provider interface.

Documents used to live on the local filesystem, with the absolute path
written into the database. That works on one machine and nowhere else: a
second API replica cannot read what the first one wrote, so the service
could never be scaled horizontally, and the path in the database leaked the
host's directory layout into anything that read it.

Business logic now speaks to this interface and never learns which provider
is behind it. What is stored in the database is an opaque **key**, never a
path, so the same row means the same object whichever backend holds it.

A key looks like ``documents/<workspace-id>/<opaque-name>.<ext>``. It is
generated by the application, never taken from the client, so traversal and
overwrite are impossible by construction rather than by sanitising well
enough.
"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime

#: Keys are restricted to this shape. Anything else is rejected before it
#: reaches a provider, so a malformed key cannot be turned into "../" on a
#: filesystem or an unexpected prefix in a bucket.
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,511}$")


class StorageError(RuntimeError):
    """A storage operation failed.

    Providers raise this rather than leaking a backend-specific exception,
    so callers do not have to know whether they are talking to a filesystem
    or to S3 in order to handle a failure.
    """


class ObjectNotFound(StorageError):
    """The requested key does not exist."""


@dataclass(frozen=True)
class ObjectInfo:
    """What a provider can say about a stored object."""

    key: str
    size: int
    #: Provider-reported content type, when it records one.
    content_type: str | None = None
    modified_at: datetime | None = None
    #: Backend-specific extras (etag, storage class). Never rendered to a
    #: user: it can carry infrastructure detail.
    metadata: dict = field(default_factory=dict)


def validate_key(key: str) -> str:
    """Reject anything that is not a well-formed storage key.

    Called by every provider before touching a backend. The application
    generates keys itself, so a bad one means a bug or a tampered database
    row, and either is worth refusing loudly.
    """
    if not key or not _KEY_PATTERN.match(key):
        raise StorageError(f"Malformed storage key: {key!r}")
    # Belt and braces: the pattern already excludes a leading dot, but a
    # traversal segment anywhere in the key must never reach a provider.
    if ".." in key.split("/"):
        raise StorageError(f"Storage key contains a traversal segment: {key!r}")
    return key


class StorageProvider(ABC):
    """Where document bytes live.

    Implementations must be safe to construct once and reuse across
    requests and worker processes.
    """

    #: Identifier recorded on the document row, so a stored object can
    #: always be traced back to the backend that holds it even after the
    #: configured provider changes.
    name: str = "base"

    @abstractmethod
    def put(self, key: str, source_path: str, *, content_type: str | None = None) -> ObjectInfo:
        """Store the file at ``source_path`` under ``key``.

        Takes a path rather than bytes: uploads arrive as files on disk
        after quarantine scanning, and streaming a large PDF through memory
        to store it would undo the point of streaming it in.

        **The source is consumed.** On success the file at ``source_path`` no
        longer exists. Callers hand over a quarantined upload and are done
        with it; a provider that copied instead would leave that file on
        local disk on every upload, which is a slow leak on exactly the
        busiest path in the system.
        """

    @abstractmethod
    def download_to(self, key: str, destination_path: str) -> str:
        """Copy the object to a local path and return that path.

        The ingestion pipeline needs real bytes on a real filesystem: PDF
        extraction and the embedding model both read files.
        """

    @abstractmethod
    def delete(self, key: str) -> bool:
        """Remove the object. True when something was removed.

        Deleting an object that is already gone is success, not an error:
        cleanup runs repeatedly and must be idempotent.
        """

    @abstractmethod
    def exists(self, key: str) -> bool:
        """Whether the object is present."""

    @abstractmethod
    def info(self, key: str) -> ObjectInfo:
        """Metadata for one object. Raises ObjectNotFound if absent."""

    @abstractmethod
    def list(self, prefix: str = "", limit: int = 1000) -> list[ObjectInfo]:
        """Objects under ``prefix``, bounded by ``limit``.

        Used by the cleanup task to find orphans. Bounded on purpose: an
        unbounded listing of a large bucket is how a maintenance job becomes
        an outage.
        """

    @abstractmethod
    def signed_url(self, key: str, *, expires_in: int, filename: str | None = None) -> str | None:
        """A time-limited URL for the object, or None if unsupported.

        A provider that cannot issue one returns None, and the download
        endpoint streams the bytes itself instead. Returning a permanent or
        unauthenticated URL is never an acceptable substitute.
        """

    def health(self) -> dict:
        """Whether the backend is reachable, for the health endpoint."""
        return {"provider": self.name, "status": "unknown"}
