"""
Alembic environment.

The database URL comes from the application's own settings rather than
alembic.ini, so `alembic upgrade head` can never be pointed at a different
database than the one the service will use, and no credentials are
committed.

Importing app.models is what populates Base.metadata; without it
autogenerate would compare the live database against an empty metadata and
cheerfully emit a migration that drops every table.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from app.core.config import settings

# Registers every mapped class on Base.metadata. Imported for the side
# effect, which is the whole point.
import app.models  # noqa: F401  isort:skip
from app.core.database import Base  # noqa: E402  isort:skip

config = context.config

if config.config_file_name is not None:
    # disable_existing_loggers defaults to True, which switches off every
    # logger that is not named in alembic.ini. When migrations run in-process
    # -- the test suite does exactly this -- that silently disables the whole
    # researchsphere.* hierarchy and the application stops logging with no
    # error anywhere.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

target_metadata = Base.metadata


def _common_options() -> dict:
    """Options shared by the offline and online paths.

    ``compare_type`` catches a column whose type changed in the models but
    not in the database, which is otherwise silently missed.

    ``render_as_batch`` makes SQLite rewrite a table when a migration alters
    a column, since SQLite cannot ALTER in place. It is a no-op on
    PostgreSQL, and without it a future migration would apply in production
    and fail on a developer's SQLite database.
    """
    return {
        "target_metadata": target_metadata,
        "compare_type": True,
        "render_as_batch": True,
        # Alembic's own bookkeeping table is not part of the models, so it
        # must be excluded or autogenerate would try to drop it.
        "include_object": _include_object,
    }


def _include_object(obj, name, type_, reflected, compare_to):
    """Keep Alembic's version table out of autogenerated diffs."""
    if type_ == "table" and name == "alembic_version":
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of executing it.

    Used by `alembic upgrade head --sql` to hand a reviewed script to a DBA
    rather than letting the application mutate the schema itself.
    """
    context.configure(
        url=settings.DATABASE_URL,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_common_options(),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, **_common_options())
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
