"""indexes for paginated list queries

Revision ID: f3de45f7daf0
Revises: 480fb499dfb7
Created: 2026-09-10 18:00:11.274104+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "f3de45f7daf0"
down_revision: str | None = "480fb499dfb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_messages_session_created", ["session_id", "created_at"], unique=False
        )

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_sessions_workspace_user_updated",
            ["workspace_id", "user_id", "updated_at"],
            unique=False,
        )

    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.create_index("ix_connectors_workspace", ["workspace_id"], unique=False)

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_chunks_document_index", ["document_id", "chunk_index"], unique=False
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_workspace_created", ["workspace_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_documents_workspace_status", ["workspace_id", "status"], unique=False
        )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reports_workspace_user_created",
            ["workspace_id", "user_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_workspace_user_created")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_workspace_status")
        batch_op.drop_index("ix_documents_workspace_created")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_document_chunks_document_index")

    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.drop_index("ix_connectors_workspace")

    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_sessions_workspace_user_updated")

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_messages_session_created")

    # ### end Alembic commands ###
