"""workspace members and invitations

Revision ID: 480fb499dfb7
Revises: dfe33d58e393
Created: 2026-09-10 14:04:01.256224+00:00
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

revision: str = "480fb499dfb7"
down_revision: str | None = "dfe33d58e393"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("invited_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workspace_invitations", schema=None) as batch_op:
        batch_op.create_index("ix_workspace_invitations_email", ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workspace_invitations_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            "ix_workspace_invitations_workspace_id", ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("invited_by", sa.String(length=36), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_workspace_member"),
    )
    with op.batch_alter_table("workspace_members", schema=None) as batch_op:
        batch_op.create_index("ix_workspace_members_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_workspace_members_workspace_id", ["workspace_id"], unique=False)
        batch_op.create_index(
            "uq_workspace_single_owner",
            ["workspace_id"],
            unique=True,
            sqlite_where=sa.text("role = 'owner'"),
            postgresql_where=sa.text("role = 'owner'"),
        )

    # ### end Alembic commands ###

    # Every workspace that existed before membership had exactly one person
    # with access: its owner. Without this backfill those workspaces would
    # have no members at all and their owners would lose access the moment
    # authorization starts reading workspace_members.
    #
    # Written as SQL against the connection rather than through the ORM: a
    # migration must not depend on the shape the models happen to have when
    # it is finally run, which may be several releases later.
    connection = op.get_bind()
    now = datetime.now(UTC).replace(tzinfo=None)
    workspaces = connection.execute(
        sa.text("SELECT id, owner_id, created_at FROM workspaces WHERE owner_id IS NOT NULL")
    ).fetchall()

    for workspace_id, owner_id, created_at in workspaces:
        connection.execute(
            sa.text(
                "INSERT INTO workspace_members "
                "(id, workspace_id, user_id, role, invited_by, joined_at, created_at, updated_at) "
                "VALUES (:id, :workspace_id, :user_id, 'owner', NULL, :joined_at, :now, :now)"
            ),
            {
                "id": str(uuid.uuid4()),
                "workspace_id": workspace_id,
                "user_id": owner_id,
                # The owner has been a member since the workspace existed;
                # dating it now would misreport the history.
                "joined_at": created_at or now,
                "now": now,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_members", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_workspace_single_owner",
            sqlite_where=sa.text("role = 'owner'"),
            postgresql_where=sa.text("role = 'owner'"),
        )
        batch_op.drop_index("ix_workspace_members_workspace_id")
        batch_op.drop_index("ix_workspace_members_user_id")

    op.drop_table("workspace_members")
    with op.batch_alter_table("workspace_invitations", schema=None) as batch_op:
        batch_op.drop_index("ix_workspace_invitations_workspace_id")
        batch_op.drop_index(batch_op.f("ix_workspace_invitations_token_hash"))
        batch_op.drop_index("ix_workspace_invitations_email")

    op.drop_table("workspace_invitations")
    # ### end Alembic commands ###
    # Dropping the tables discards the backfilled owner rows too. That is
    # correct: workspaces.owner_id is untouched by this migration and remains
    # the access model the previous release used.
